### ISSUE TITLE
Orb unable to build .NET Core Lambda Functions

### ISSUE THREAD

**Issue by jacoblever** [CircleCI-Public/aws-sam-serverless-orb#13]
### Orb version

`1.0.2`

### What happened

I'm trying to deploy [this](https://github.com/jacoblever/chameleon/blob/ef34436c6e041daa609abb983ed807cb5ca60428/template.yaml) AWS SAM template, which contains an AWS lambda function using the `dotnetcore2.1` runtime.

When running the build with this the following config (see [code here](https://github.com/jacoblever/chameleon/blob/890329383ce11e2fe41891c3773b30e752a35230/.circleci/config.yml#L19-L29))
```
      - aws-serverless/deploy:
          name: deploy-backend-staging
          # requires: and filters: settings removed for brevity
          stack-name: chameleon-game-test
          template: ./template.yaml
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-1hoa4cv2sc075
```

I got the following error (link to build [here](https://circleci.com/gh/jacoblever/chameleon/515?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)):
```
Starting Build inside a container
Building resource 'ChameleonFunction'

Build Failed
Error: We do not support building .NET Core Lambda functions within a container. Try building without the container. Most .NET Core functions will build successfully.
```

This led me to add the `use-container: false` parameter (the config with that change is [here](https://github.com/jacoblever/chameleon/blob/ef34436c6e041daa609abb983ed807cb5ca60428/.circleci/config.yml#L19-L30)), but this resulted in the following error (link to build [here](https://circleci.com/gh/jacoblever/chameleon/517?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link))
```
Building resource 'ChameleonFunction'

Build Failed
Error: DotnetCliPackageBuilder:Resolver - No dotnet cli executable found!
```

Is there some extra config I need to include the dotnet cli and allow the orb to build dotnet Lambda Functions?

### Expected behavior

That the build should successfully build and deploy the Lambda Function (as defined in the SAM template) to AWS.
