### ISSUE TITLE
Container image (Docker) support for Lambda functions

### ISSUE THREAD

**Issue by bjfletcher** [CircleCI-Public/aws-sam-serverless-orb#24]
## What happened:

Last month, AWS released [Container Image Support for Lambda functions](https://aws.amazon.com/blogs/compute/using-container-image-support-for-aws-lambda-with-aws-sam/) which allows us to define Dockerfiles, build images using these, and run functions within them.

So I've written template.yaml to include the container image definition:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: <removed>.dkr.ecr.eu-west-1.amazonaws.com/<removed>:latest
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
      DockerTag: latest
```

(where `<removed>`s were actual values.)

and .circle/xconfig.yml as:

```yaml
version: 2.1
orbs:
  aws-sam: circleci/aws-sam-serverless@2.1.0
workflows:
  build_and_deploy:
    jobs:
      - aws-sam/deploy:
          s3-bucket: hello
          stack-name: hello
          template: ./template.yaml
```

Obviously `s3-bucket` isn't needed as SAM deploys container images to ECR rather than S3. What's needed instead of `s3-bucket` is something like `image-repository`.

If I tried running the above on CircleCI, it fails at the `sam package` stage:

`Error: Missing option '--image-repository' or '--image-repositories'`

I tried adding a `samconfig.yoml` with:

```
version=0.1

[default.package.parameters]
image_repository = "<removed>.dkr.ecr.eu-west-1.amazonaws.com/<removed>"

[default.deploy.parameters]
image_repository = "<removed>.dkr.ecr.eu-west-1.amazonaws.com/<removed>"
```

Then the `package` stage worked but `deploy` didn't.

## Expected behavior:

It packages and deploys the container image.

**Comment by vleandersson** [comment]
Not sure about the workaround for CircleCi, but this seems to be an issue in SAM deploys where you are required to add the flag '--image-repository' or '--image-repositories'` and `ImageUri` is ignored.

**Comment by leehanchung** [comment]
I am getting the same error on Bitbucket Pipeline:

bitbucket_pipeline.yml
```yml
 - pipe: atlassian/aws-sam-deploy:1.2.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                S3_BUCKET: 'deployment-bucket'
                STACK_NAME: 'deploymentFunction'
                SAM_CONFIG: "samconfig.toml"
                CAPABILITIES: ['CAPABILITY_IAM']
                WAIT: 'true'
                WAIT_INTERVAL: 60

```

Inside `samconfig.toml`:
```toml
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deploymentFunction"
s3_bucket = "deployment-bucket"
s3_prefix = "deployment-prefix"
capabilities = "CAPABILITY_IAM"
image_repositories = ["deploymentFunction=<removed>.dkr.ecr.us-east-1.amazonaws.com/deployment-function"]
confirm_changeset = false
```

Output:
```
INFO: Using default authentication with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.
INFO: Start package...
	SAM CLI now collects telemetry to better understand customer needs.
	You can OPT OUT and disable telemetry collection by setting the
	environment variable SAM_CLI_TELEMETRY=0 in your shell.
	Thanks for your help!
	Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html
Usage: sam package [OPTIONS]
Try 'sam package -h' for help.
Error: Missing option '--image-repository' or '--image-repositories'
✖ Failed SAM package.
```
