### ISSUE TITLE
Missing environment variable interpolation.

### ISSUE THREAD

**Issue by daroot** [CircleCI-Public/aws-sam-serverless-orb#27]
## Orb version:

circleci/aws-sam-serverless@3.0.0

## What happened:

environment variables cannot be passed to some string parameters.

for instance: 

```yaml
 deploy-dev:                               
   executor: sam/default                   
   steps:                                  
     - checkout                            
     - sam/install                         
     - sam/deploy:                         
         stack-name: "myapp-dev"      
         template: template.yaml           
         s3-bucket: $S3_ARTIFACT_BUCKET
```

produces an error `Invalid bucket name "$S3_ARTIFACT_BUCKET": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
`
when S3_ARTIFACT_BUCKET is set via context.

## Expected behavior:

Deploys, using the --s3-bucket parameter set via context variable S3_ARTIFACT_BUCKET.

## Additional Information:

This appears to be a function of how this orb uses params to set env variables then builds commands via the env variables, thus not resolving them if they are references to shell variables themselves.   

I'm relatively new to circleci and wasn't sure if this was just me misusing circleci's configuration, but testing this with a few other orbs works correctly.  And it even appears in the documents for aws-sam-serverless to work for image-repositories.   

Of note, that image-repositories uses an `eval echo` inside the evaluation of it, which presumably in turn causes the appropriate shell variable to be interpolated.   

`image-repositories` uses this eval in the array evaluation, `template` has its own eval echo construct, but `stack-name` `s3-bucket`, `profile-name`, and `parameter-overrides` do not appear to have this additional expansion, which means those values cannot inherit from a context or project environment variable.

I think resolving this is as simple as adding the eval echo wrappers to the other possible parameters, and I can't think of any scenarios where this might break things.
