### ISSUE TITLE
CloudFormation: Review in Progress

### ISSUE THREAD

**Issue by petrogad** [CircleCI-Public/aws-sam-serverless-orb#34]
## What happened:

```
version: 2.1

orbs:
  #orb
  aws-serverless: circleci/aws-sam-serverless@3.1.0

workflows:
  build_and_deploy:
    jobs:
      - aws-serverless/deploy:
          name: deploy-staging
          s3-bucket: bucket
          stack-name: staging-serverless-actions
          template: template.yaml
```

Executing this created a cloudformation in "REVIEW_IN_PROGRESS" vs pushing it all the way through. Curious if the CF needs to be initially ran locally prior to being run through circleci.
