### ISSUE TITLE
Fail to deploy AWS::Serverless::StateMachine

### ISSUE THREAD

**Issue by shunwen** [CircleCI-Public/aws-sam-serverless-orb#38]
## Orb version:

3.1.0

Here is my config.yml

```yaml
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  sam: circleci/aws-sam-serverless@3.1.0

workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-production
          image-repositories: myorganisationid1234567.dkr.ecr.ap-northeast-1.amazonaws.com/my-project-name
          stack-name: my-project-name
          template: ./template.yaml
          filters:
            branches:
              only: main
```

## What happened:

I defined a statemachine resource in a SAM template.yaml as below:
```yaml
  StateMachine:
    Type: AWS::Serverless::StateMachine 
    Properties:
      Name: GetAllTickerEarningsCallsStateMachine
      DefinitionUri: ./statemachine/statemachine.asl.json
      Role: !GetAtt StateMachineRole.Arn
```

I can run `sam build` and `sam deploy` locally to deploy the statemachine. I have problem deploying it using this orb on CircleCI, got the following error message:

```
Error: Unable to upload artifact ../../statemachine/statemachine.asl.json referenced by DefinitionUri parameter of StateMachine resource.

S3 Bucket not specified, use --s3-bucket to specify a bucket name, or use --resolve-s3 to create a managed default bucket, or run sam deploy --guided
```

I tried to set `s3-bucket` option in config.yml but it failed because I already set `image-repositories`

## Expected behavior:

It is expected to deploy the statemachine as it does locally. `sam deploy` creates a managed s3 bucket (name like `aws-sam-cli-managed-default-samclisourcebucket-1n1tv1h0em72e`) for deploy use

## Additional Information:

It seems it can have both `s3_bucket` and `image_repositories` options
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
