### ISSUE TITLE
Deploy arguments parameter can't accept multiple args

### ISSUE THREAD

**Issue by rafiqhilali** [CircleCI-Public/aws-sam-serverless-orb#65]
## What happened:
Deploying a stack like this
```yml
- aws-sam-serverless/deploy:
    auth:
      - aws-cli/setup:
          role_arn: 'arn:aws:iam::**************:role/circleci-oidc-role'
          role_session_name: "deploy-local"
    arguments: '--resolve-image-repos --config-env local'
    template: template.yml
    stack_name: sample-stack
    region: eu-west-1
 ```

results in an error message: 
```
Error: No such option: --resolve-image-repos --config-env local Did you mean --resolve-image-repos?
```

I haven't tested if this issue also appears for `build_arguments` 

## Expected behavior:
Orb should be able to accept multiple arguments, either by:
* space separated arguments for `arguments` 
* a list of arguments for `arguments`
